### PR TITLE
A tiny fix B:|

### PR DESCRIPTION
**Pull request by unickorn**
It bothered me a lot xD

### CODE REVIEW

**Comment by SalmonDE** [comment]
Never spotted that. Thank you! :)

**Comment by Aericio** [comment]
silly you

**Comment by unickorn** [comment]
"xdxdxdlmao" Whaaaat B:|

**Comment by unickorn** [comment]
https://pics.onsizzle.com/inverted-mind-inc-cozylittleartblog-what-have-i-done-gods-work-source-cozylittleartblog-16712917.png

**Comment by Aericio** [comment]
lol

**Pull request merged**
